### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by mikebridge** [JosephWoodward/GlobalExceptionHandlerDotNet#11]
When I set up CORS it correctly adds Access-Control headers to non-erroring API responses.  However, they aren't generated on an unhandled error that passes through GlobalExceptionHandlerDotNet. 

Is there something else I need to do to set the proper response headers?

**Comment by slang25** [comment]
You'll need to call `.UseCors(...` before `app.UseExceptionHandler().WithConventions(...`, could you just confirm this is the case.

**Comment by paulvanbladel** [comment]
Same problem here, Cors will remove the response.
See: https://github.com/aspnet/CORS/issues/90

**Comment by slang25** [comment]
Nice find. There's a workaround in that issue where you can add a ```MaintainCorsHeader``` middleware to restore the headers that are removed, obviously not ideal. Hopefully they will fix this soon.

**Comment by mikebridge** [comment]
@paulvanbladel Thanks, adding a MaintainCorsHeader middleware to put the headers back was the only thing that worked for me.

Regardless, it doesn't seem to be a problem with GlobalExceptionHandler.
