### ISSUE TITLE
Do not restrict to return pre-defined http status codes

### ISSUE THREAD

**Issue by ozonni** [JosephWoodward/GlobalExceptionHandlerDotNet#12]
[ReturnStatusCode](https://github.com/JosephWoodward/GlobalExceptionHandlerDotNet/blob/7a568804ee60e5e6c8f60c1dc610fd18fd70c164/src/GlobalExceptionHandler/WebApi/ExceptionRuleCreator.cs#L11) forces you to return one of the http status codes defined in enum which makes it impossible to return something like `499` or any other custom http code.

**Comment by JosephWoodward** [comment]
Thanks for the PR @slang25, that's been merged and I'll get a release out very soon @ozonni.

**Comment by ozonni** [comment]
@JosephWoodward thank you. can i already get new version from nuget?

**Comment by JosephWoodward** [comment]
@ozonni This has now been released, it should show up in NuGet any minute now. I've tagged the version as a major release as it's a breaking change to consumers. Thanks again for making me aware of this.
