### ISSUE TITLE
ASP.Net Core 2.1 Issue

### ISSUE THREAD

**Issue by jculverwell** [JosephWoodward/GlobalExceptionHandlerDotNet#18]
Just upgraded to ASP.Net Core 2.1 and got this error:

InvalidOperationException: An error occurred when configuring the exception handler middleware. Either the 'ExceptionHandlingPath' or the 'ExceptionHandler' option must be set in 'UseExceptionHandler()'.

My setup before was this:

```
 app.UseExceptionHandler().WithConventions(x => {
                x.ContentType = "application/json";
                x.MessageFormatter(s => JsonConvert.SerializeObject(new
                {
                    Message = "Internal Server Error"
                }));
                x.OnError((exception, httpContext) =>
                {
                    Log.Error(exception, "WebAPI Global Exception Handler");
                    return Task.CompletedTask;
                });
            });
```

Adding `app.UseExceptionHandler("/error")` as below seems to fix it.

```
app.UseExceptionHandler("/error").WithConventions(x => {
                x.ContentType = "application/json";
                x.MessageFormatter(s => JsonConvert.SerializeObject(new
                {
                    Message = "Internal Server Error"
                }));
                x.OnError((exception, httpContext) =>
                {
                    Log.Error(exception, "WebAPI Global Exception Handler");
                    return Task.CompletedTask;
                });
            });
```

Just wanted to give you a heads up and check the workaround makes sense.  Thanks for a great repo.

**Comment by JosephWoodward** [comment]
Great, thanks for reporting this @jculverwell, I'll take a look.

**Comment by alhardy** [comment]
Was curious about this also

**Comment by slang25** [comment]
It's worth noting that this was changed in 2.1 because leaving it empty is dangerous. By default in 2.0 and below it will use the current path as the error handler path, so for us we had POST requests being "replayed" and things getting saved to the database twice etc...

**Comment by JosephWoodward** [comment]
> so for us we had POST requests being "replayed" and things getting saved to the database twice etc...

Was GlobalExceptionHandler causing them to be posted twice?

**Comment by JosephWoodward** [comment]
I've now released a beta package which resolves this (it's a major version bump as it includes some breaking changes, but they're just method renames). If you'd like to give it a try I'd love to hear how you get on with it.

The new version can be found here https://www.nuget.org/packages/GlobalExceptionHandler/4.0.0-beta1 and the release notes [here](https://github.com/JosephWoodward/GlobalExceptionHandlerDotNet/releases/tag/4.0.0-beta1).
