### ISSUE TITLE
HTTP status code within exception 

### ISSUE THREAD

**Issue by shorbachuk** [JosephWoodward/GlobalExceptionHandlerDotNet#20]
I am using this library, works great for mapping argument exceptions etc.

I have another exception type where I am calling another API. The HTTP status code is within a property in that exception. Is there or can there be a way to handle for this?

**Comment by JosephWoodward** [comment]
At the moment there isn't, but I'd be open to adding an overload to `ReturnStatusCode(...)`along the lines of:

```csharp
ReturnStatusCode(Func<Exception, HttpStatusCode>)
```

**Comment by shorbachuk** [comment]
Cool, should I work on a PR or is this something you would like to take?

**Comment by JosephWoodward** [comment]
I'm currently doing some work on the API so I can do it as a part of that 👍

**Comment by shorbachuk** [comment]
Any idea when to expect this enhancement?

**Comment by JosephWoodward** [comment]
Just finishing off the last few bits (I'm working on a major release) so it should be done in the next few days.

**Comment by JosephWoodward** [comment]
I've now released a beta package which includes this functionality (it's included within a major version bump I was working on which includes some breaking changes, but they're just method renames). If you'd like to give it a try I'd love to hear how you get on with it.

The new version can be found here https://www.nuget.org/packages/GlobalExceptionHandler/4.0.0-beta1

**Comment by shorbachuk** [comment]
I tried the beta. Agree with all the renames, they make a lot more sense. 

`x.Map<HttpStatusCodeException>().ToStatusCode(ex => (int)((HttpStatusCodeException)ex).StatusCode);`

**Comment by JosephWoodward** [comment]
I'd love to be able to pass the generic type passed in at `Map<T>` all the way down to `.ToStatusCode(Func<T, int> x)` but unfortunately my GenericFu isn't up to scratch. I'd definitely welcome a PR if you can see some options for making this better?

Another option would also be to add the following overload for those that are using (by choice or necessity) `System.Net.HttpStatusCode` which would at the very least remove the need to cast the status code to an int?

```csharp
IHandledFormatters ToStatusCode(Func<Exception, int> statusCodeResolver);
IHandledFormatters ToStatusCode(Func<Exception, HttpStatusCode> statusCodeResolver); // Could add this overload?
```

**Comment by JosephWoodward** [comment]
@shorbachuk New version with these changes have been uploaded to NuGet. Give it a whirl and let me know what you think.

![Alt Text](https://media.giphy.com/media/1GlDW1HBD3q2A/giphy.gif)

**Comment by shorbachuk** [comment]
I just tried it. Its working really great, exactly what I needed.

**Comment by JosephWoodward** [comment]
Great, I'll close this off then. Thanks for the feature suggestion(s)!

**Comment by shorbachuk** [comment]
Any plans to take this out of beta?

**Comment by JosephWoodward** [comment]
@shorbachuk Yeah, can do it this weekend.

**Comment by JosephWoodward** [comment]
@shorbachuk Just realised I didn't do this! Will do it today, I promise!
