### ISSUE TITLE
Logging Session Id

### ISSUE THREAD

**Issue by dharanish** [JosephWoodward/GlobalExceptionHandlerDotNet#29]

**Comment by dharanish** [comment]
In the request pipeline if I use app.UseSession() after app.UseGlobalExceptionHandler(...), the httpcontext session object will not be available. 

Is there any workaround for it?

**Comment by JosephWoodward** [comment]
Oh really? That's interesting, I'll have to take a look.

**Comment by JosephWoodward** [comment]
Didn't mean the close the issue, I pressed the wrong comment button 😖

**Comment by dharanish** [comment]
If we add app.UseSession() before exception handler we can session object

**Comment by JosephWoodward** [comment]
I presume this issue can be closed now? I'll close it, but if you're still having issues please feel free to reopen it.
